export const FETCH_TOKEN_STATISTIC_REQUEST = 'tokens/FETCH_TOKEN_STATISTIC_REQUEST';
export const FETCH_TOKEN_STATISTIC_SUCCESS = 'tokens/FETCH_TOKEN_STATISTIC_SUCCESS';
export const FETCH_TOKEN_STATISTIC_ERROR = 'tokens/FETCH_TOKEN_STATISTIC_ERROR';
